
networks:
  net_private:
    driver: bridge
    internal: true

  net_public:
    driver: bridge
 
volumes:
  consul_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/consul_data
  
  vault_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/vault_data
  
  fs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/fs
  
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/db_data

services:
  consul:
    container_name: Consul
    hostname: consul
    build:
      context: ./source/services/consul
      dockerfile: Dockerfile
    env_file:
      - ./configs.env
    environment:
      PYTHONPATH: "/"
      PYTHONUNBUFFERED: "1"
      SERVICE_NAME: "consul"
      SERVICE_PORT: 8501
      SERVICE_TAGS: "infra,kv,core"
      CONSUL_HTTP_TOKEN_FILE: "fs/secrets/consul_token_for_consul"
    volumes:
      - ./configs.env:/configs.env:ro
      - ./source/core:/core:ro
      - ./source/base:/base:ro
      - ./source/services:/services:ro
      - ./source/interfaces:/interfaces:ro
      - ./source/entities:/entities:ro
      - ./source/adapters:/adapters:ro
      - ./source/services/consul/config:/config:rw
      - ./source/services/consul/app:/app:ro
      # данные и слой fs/*
      - consul_data:/consul/data
      - fs:/certs
      - fs:/markers
      - fs:/secrets
      - fs:/tmp
    networks:
      - net_private
    ports:
      - "8500:8500"
      - "8501:8501"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.consul-ui.rule=Host(`consul.terminal.speculorg.localhost`)"
      - "traefik.http.routers.consul-ui.entrypoints=websecure"
      - "traefik.http.routers.consul-ui.tls=true"
      - "traefik.http.services.consul-ui.loadbalancer.server.port=8501"
    restart: unless-stopped

  vault:
    container_name: Vault
    hostname: vault
    build:
      context: ./source/services/vault
      dockerfile: Dockerfile
    cap_add:
      - IPC_LOCK 
    env_file:
      - ./configs.env
    environment:
      PYTHONPATH: "/"
      PYTHONUNBUFFERED: "1"
      SERVICE_NAME: "vault"
      SERVICE_PORT: 8200
      SERVICE_TAGS: "infra,ca,core"
      CONSUL_HTTP_TOKEN_FILE: "fs/secrets/consul_token_for_vault"
    volumes:
      - ./configs.env:/configs.env:ro
      - ./source/core:/core:ro
      - ./source/base:/base:ro
      - ./source/services:/services:ro
      - ./source/interfaces:/interfaces:ro
      - ./source/entities:/entities:ro
      - ./source/adapters:/adapters:ro
      - ./source/services/vault/app:/app:ro
      - ./source/services/vault/config:/config:rw
      - vault_data:/vault/file
      - fs:/certs
      - fs:/markers
      - fs:/secrets
      - fs:/tmp
    networks:
      - net_private
    ports:
      - "8200:8200"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault-ui.rule=Host(`vault.terminal.speculorg.localhost`)"
      - "traefik.http.routers.vault-ui.entrypoints=websecure"
      - "traefik.http.routers.vault-ui.tls=true"
      - "traefik.http.services.vault-ui.loadbalancer.server.port=8200"
    restart: unless-stopped

  traefik:
    container_name: Traefik
    hostname: traefik
    build:
      context: ./source/services/traefik
      dockerfile: Dockerfile
    env_file:
      - ./configs.env
    environment:
      PYTHONPATH: "/"
      PYTHONUNBUFFERED: "1"
      SERVICE_NAME: "traefik"
      SERVICE_PORT: 8443
      SERVICE_TAGS: "infra,edge,core"
      CONSUL_HTTP_TOKEN_FILE: "fs/secrets/consul_token_for_traefik"
    volumes:
      - ./configs.env:/configs.env:ro
      - ./source/core:/core:ro
      - ./source/base:/base:ro
      - ./source/services:/services:ro
      - ./source/interfaces:/interfaces:ro
      - ./source/entities:/entities:ro
      - ./source/adapters:/adapters:ro
      - ./source/services/traefik/app:/app:ro
      - ./source/services/traefik/config:/config:rw
      - fs:/certs
      - fs:/markers
      - fs:/secrets
      - fs:/tmp
    networks:
      - net_private
      - net_public
    ports:
      - "8080:8080"
      - "8443:8443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.terminal.speculorg.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
    restart: unless-stopped
