from __future__ import annotations

from pathlib import Path
from typing import Optional

from core._interfaces import IConfigs, IFS, ILogger, IMarkers


def traefik_bootstrap(*, cfg: IConfigs, fs: IFS, markers: IMarkers, log: Optional[ILogger] = None) -> None:
    """
    TERM-1 bootstrap для Traefik (идемпотентно):

    Задача:
    - Сгенерировать secure static config для Traefik, использующий Consul Catalog provider.
    - Consul Catalog: exposedByDefault=false, token (из CONSUL_HTTP_TOKEN_FILE), endpoint https://consul:<https_port> (mTLS).
    - File provider: /config (dynamic_https.yml): TLS options + serversTransports (upstream mTLS).

    Выходной артефакт:
    - /config/traefik_https.generated.yml

    Примечание:
    - Маркеры выставляет BootstrapPolicy ядра (здесь НЕ выставляем).
    """
    _ = markers  # маркеры управляются ядром

    def _log(msg: str, **fields) -> None:
        if log is None:
            return
        log.info(msg, fields=fields or None)

    domain_root = str(cfg.get("GLOBAL_DOMAIN_ROOT", "terminal.local"))
    consul_host = str(cfg.get("CONSUL_HOST", "consul"))
    consul_https_port = int(cfg.get("CONSUL_HTTPS_PORT", 8501) or 8501)

    token_file = str(cfg.get("CONSUL_HTTP_TOKEN_FILE", "") or "").strip()
    if not token_file:
        raise RuntimeError("traefik_bootstrap_missing_consul_token_file")

    token_path = Path(token_file)
    token = fs.read_text(token_path).strip() if fs.exists(token_path) else ""
    if not token:
        raise RuntimeError("traefik_bootstrap_empty_consul_token")

    out = Path("/config/traefik_https.generated.yml")

    _log(
        "traefik_bootstrap:start",
        domain_root=domain_root,
        consul=f"{consul_host}:{consul_https_port}",
        token_file=str(token_path),
        token_len=len(token),
        out=str(out),
    )

    # TERM-1: defaultRule НЕ задаём.
    # Для Consul Catalog используется exposedByDefault=false и явные теги (traefik.enable=true + router/service tags).
    content = f"""# Generated by traefik_bootstrap (TERM-1)
log:
  level: INFO

accessLog: {{}}

api:
  dashboard: true

entryPoints:
  websecure:
    address: ":8443"

providers:
  file:
    directory: /config
    watch: true

  consulCatalog:
    exposedByDefault: false
    endpoint:
      address: \"{consul_host}:{consul_https_port}\"
      scheme: \"https\"
      token: \"{token}\"
      tls:
        ca: \"/fs/terminal/certs/ca.crt\"
        cert: \"/fs/terminal/certs/traefik.crt\"
        key: \"/fs/terminal/certs/traefik.key\"
"""

    fs.write_text_atomic(out, content)

    if not fs.exists(out):
        raise RuntimeError("traefik_bootstrap_write_failed")

    _log("traefik_bootstrap:ok", out=str(out), bytes=len(content))
