log:
  level: INFO

accessLog: {}

api:
  dashboard: true

entryPoints:
  websecure:
    address: ":8443"
    http:
      tls:
        options: mtls@file

providers:
  file:
    directory: /config
    watch: true

  consulCatalog:
    exposedByDefault: false
    defaultRule: "Host(`{{ .Name }}.terminal.speculorg.localhost`)"
    endpoint:
      address: "consul:8501"
      scheme: "https"
      token: "bbcdc58c-dc08-3b11-5439-c82123d151ef"
      tls:
        ca: "/fs/terminal/certs/ca.crt"
        cert: "/fs/terminal/certs/traefik.crt"
        key: "/fs/terminal/certs/traefik.key"
