from enum import Enum

class EventEnum(str, Enum):
    HEARTBEAT = "HEARTBEAT"
    PUBLISH_STATE = "PUBLISH_STATE"
    WATCH = "WATCH"
    RELOAD = "RELOAD"
    REQUEST = "REQUEST"
    RETRY = "RETRY"
    TIMEOUT = "TIMEOUT"


# Черновик event codes for Speculorg.Terminal (FSM + Policies + Services)
EVENTS = {
    'system.start': 'Запуск процесса сервиса (entrypoint).', 
    'system.stop': 'Остановка процесса сервиса (entrypoint завершён).', 
    'configs.load.start': 'Начало загрузки конфигурации (ENV/.env/модель).', 
    'configs.load.ok': 'Конфигурация загружена и провалидирована.', 
    'configs.load.error': 'Ошибка загрузки/валидации конфигурации.', 
    'deps.build.start': 'Начало сборки зависимостей (composition-root).', 
    'deps.build.ok': 'Зависимости собраны: Configs/Logger/FS/Markers/Net/FSM.', 
    'deps.build.error': 'Ошибка сборки зависимостей.', 
    'service.run.start': 'Запуск сервиса (BaseService.run).', 
    'service.run.stop': 'Остановка сервиса (BaseService.stop).', 
    'service.restart': 'Перезапуск сервиса по команде.', 
    'fsm.run.start': 'Старт цикла FSM.', 
    'fsm.run.error': 'Фатальная ошибка FSM.', 
    'fsm.enter': 'Попытка входа в состояние.', 
    'fsm.entered': 'Вход в состояние выполнен.', 
    'fsm.transition': 'Переход FSM в новое состояние.', 
    'fsm.state.publish.start': 'Публикация состояния (например, в KV).', 
    'fsm.state.publish.ok': 'Состояние опубликовано.', 
    'fsm.state.publish.error': 'Ошибка публикации состояния.', 
    'policy.marker.missing': 'Отсутствуют обязательные маркеры stage-gate для состояния.', 
    'policy.marker.ok': 'Все обязательные маркеры состояния присутствуют.', 
    'daemon.runmode.detect.start': 'Детектирование режима запуска (FIRST/RECOVERY/NORMAL).', 
    'daemon.runmode.detect.ok': 'Режим запуска определён.', 
    'daemon.runmode.detect.error': 'Ошибка детектирования режима запуска.', 
    'daemon.mode.selected': 'Выбран режим запуска демона (http|https).', 
    'daemon.start.start': 'Запуск демона с выбранным режимом (http|https).', 
    'daemon.start.ok': 'Демон запущен.', 
    'daemon.start.error': 'Ошибка запуска демона.', 
    'daemon.stop.start': 'Остановка демона.', 
    'daemon.stop.ok': 'Демон остановлен.', 
    'daemon.stop.error': 'Ошибка остановки демона.', 
    'daemon.restart.start': 'Перезапуск демона.', 
    'daemon.restart.ok': 'Демон перезапущен.', 
    'daemon.restart.error': 'Ошибка перезапуска демона.', 
    'daemon.switch.start': 'Переключение режима демона (http→https) путём смены start_cmd.', 
    'daemon.switch.ok': 'Режим демона переключён.', 
    'daemon.switch.error': 'Ошибка переключения режима демона.', 
    'net.port.wait.start': 'Ожидание доступности порта/сокета.', 
    'net.port.wait.ok': 'Порт доступен.', 
    'net.port.wait.timeout': 'Таймаут ожидания порта.', 
    'net.http.probe.ok': 'HTTP-проба успешна.', 
    'net.http.probe.error': 'Ошибка HTTP-пробы.', 
    'net.https.probe.ok': 'HTTPS-проба успешна.', 
    'net.https.probe.error': 'Ошибка HTTPS-пробы.', 
    'bootstrap.apply.start': 'Выполнение одноразовых действий BOOTSTRAPPING.', 
    'bootstrap.apply.ok': 'Одноразовые действия успешно выполнены.', 
    'bootstrap.apply.error': 'Ошибка при выполнении одноразовых действий.', 
    'securing.tokens.apply.start': 'Применение токенов/секретов от Consul.', 
    'securing.tokens.apply.ok': 'Токены/секреты применены.', 
    'securing.tokens.apply.error': 'Ошибка применения токенов/секретов.', 
    'securing.tls.validate.start': 'Валидация TLS/PEM/цепочки доверия.', 
    'securing.tls.validate.ok': 'TLS/PEM валидны.', 
    'securing.tls.validate.error': 'Ошибка валидации TLS/PEM.', 
    'registrar.register.start': 'Регистрация сервиса в Consul Catalog.', 
    'registrar.register.ok': 'Сервис зарегистрирован в Consul Catalog.', 
    'registrar.register.error': 'Ошибка регистрации в Consul Catalog.', 
    'state.starting': 'STATE=STARTING.', 
    'state.initializing': 'STATE=INITIALIZING.', 
    'state.bootstrapping': 'STATE=BOOTSTRAPPING.', 
    'state.securing': 'STATE=SECURING.', 
    'state.registering': 'STATE=REGISTERING.',
    'state.running': 'STATE=RUNNING.', 
    'state.paused': 'STATE=PAUSED.', 
    'state.degraded': 'STATE=DEGRADED.', 
    'state.error': 'STATE=ERROR.', 
    'state.stopping': 'STATE=STOPPING.', 
    'state.stopped': 'STATE=STOPPED.', 
    'marker.set.ok': 'Маркер записан.', 
    'marker.set.error': 'Ошибка записи маркера.', 
    'marker.delete.ok': 'Маркер удалён.', 
    'marker.delete.error': 'Ошибка удаления маркера.', 
    'fs.ensure_layout.ok': 'Структура каталогов FS создана/проверена.', 
    'fs.ensure_layout.error': 'Ошибка инициализации структуры FS.', 
    'fs.atomic_read.ok': 'Файл прочитан атомарно.', 
    'fs.atomic_read.error': 'Ошибка атомарного чтения файла.', 
    'fs.atomic_write.ok': 'Файл записан атомарно.', 
    'fs.atomic_write.error': 'Ошибка атомарной записи файла.', 
    'config.hash': 'Сумма конфигурации вычислена.', 
    'config.keys.missing': 'Отсутствуют необходимые ключи конфигурации.', 
    'config.value.invalid': 'Некорректное значение параметра конфигурации.', 
    'err.precondition': 'Нарушено предусловие (например, отсутствует обязательный маркер).', 
    'err.timeout': 'Таймаут операции.', 
    'err.net': 'Сетевая ошибка/порт недоступен.', 
    'err.proc': 'Ошибка управления процессом демона.', 
    'err.config': 'Ошибка конфигурации.', 
    'err.io': 'Ошибка ввода-вывода.', 
    'err.json': 'Ошибка обработки JSON.', 
    'err.perms': 'Ошибка прав доступа/разрешений.', 
    'err.unexpected': 'Непредвиденная ошибка.'
}

