from enum import Enum

class StateEnum(str, Enum):
    STARTING = "STARTING"
    BOOTSTRAPPING = "BOOTSTRAPPING"
    INITIALIZING = "INITIALIZING"
    SECURING = "SECURING"
    TLS_TRANSITION = "TLS_TRANSITION"
    REGISTERING = "REGISTERING"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    DEGRADED = "DEGRADED"
    ERROR = "ERROR"
    STOPPING = "STOPPING"
    STOPPED = "STOPPED"
