from __future__ import annotations
from typing import Protocol, runtime_checkable
from entities.state_enum import StateEnum

@runtime_checkable
class IFSM(Protocol):
    def run(self) -> None: ...
    def on_enter(self, state: StateEnum) -> None: ...
    def publish_state(self) -> None: ...
    def configure_tls(self, run_profile, net, restart_cb, resolve_port_cb, current_mode: str = "http") -> None: ...
    def precheck_stage_gates(self, state) -> tuple[bool, list[str]]: ...
