from __future__ import annotations
from typing import Protocol, runtime_checkable, Iterable, Optional

@runtime_checkable
class IFS(Protocol):
    def atomic_read_text(self, path: str) -> str: ...
    def atomic_write_text(self, path: str, data: str) -> None: ...
    def exists(self, path: str) -> bool: ...
    def list(self, path: str, *, recursive: bool = False) -> Iterable[str]: ...
    def remove(self, path: str) -> None: ...
    def ensure_dir(self, path: str, *, mode: int = 0o755) -> None: ...
    def set_perms(self, path: str, *, mode: int, owner: Optional[int] = None, group: Optional[int] = None) -> None: ...
