from __future__ import annotations
from typing import Protocol, runtime_checkable, Callable

BytesLike = bytes | bytearray | memoryview

@runtime_checkable
class IFS(Protocol):
    """Единый интерфейс локального тома fs/*.
    Операции атомарны. Права и владельцы валидируются политикой FS.
    """
    # базовые операции
    def ensure_layout(self) -> None: ...
    def safe_list(self, path: str) -> list[str]: ...
    def exists(self, path: str) -> bool: ...
    def listdir(self, path: str) -> list[str]: ...
    def remove(self, path: str) -> None: ...
    def makedirs(self, path: str, mode: int = 0o755) -> None: ...
    # атомарные чтение/запись
    def atomic_write(self, path: str, data: BytesLike, mode: int = 0o644) -> None: ...
    def atomic_write_text(self, path: str, text: str, mode: int = 0o644, encoding: str = "utf-8") -> None: ...
    def atomic_read(self, path: str) -> bytes: ...
    def atomic_read_text(self, path: str, encoding: str = "utf-8") -> str: ...
    # watcher (упрощённый поллинг; P1-стаб)
    def start_file_watch(self, paths: list[str], on_change: Callable[[list[str]], None], poll_interval_ms: int) -> "IWatcher": ...

@runtime_checkable
class IWatcher(Protocol):
    def stop(self) -> None: ...
