from __future__ import annotations
from typing import Protocol, Optional, Dict

class IKV(Protocol):
    """Контракт KV-хранилища с индексом модификации.
    Все чтения возвращают пару (modify_index, payload_or_None).
    CAS использует тот же modify_index.
    """

    # Текстовые операции
    def read_text(self, key: str) -> tuple[int, Optional[str]]: ...
    def put_text(self, key: str, value: str) -> None: ...
    def cas_text(self, key: str, value: str, modify_index: int) -> bool: ...

    # JSON-операции (UTF-8)
    def read_json(self, key: str) -> tuple[int, Optional[Dict]]: ...
    def put_json(self, key: str, obj: Dict) -> None: ...
    def cas_json(self, key: str, obj: Dict, modify_index: int) -> bool: ...
