from __future__ import annotations
from typing import Protocol, runtime_checkable, Optional, Tuple, Any

@runtime_checkable
class IKV(Protocol):
    def get_text(self, key: str) -> Optional[str]: ...
    def put_text(self, key: str, value: str) -> None: ...
    def cas_text(self, key: str, expected_index: int, value: str) -> Tuple[bool, int]: ...

    def get_json(self, key: str) -> Optional[Any]: ...
    def put_json(self, key: str, value: Any) -> None: ...
    def cas_json(self, key: str, expected_index: int, value: Any) -> Tuple[bool, int]: ...
