from __future__ import annotations
from typing import Protocol, runtime_checkable, Optional, Mapping, Any
from entities.log_level_enum import LogLevelEnum

@runtime_checkable
class ILogger(Protocol):
    def log(self, level: LogLevelEnum, message: str, *, svc: Optional[str] = None,
            state: Optional[str] = None, event: Optional[str] = None,
            details: Optional[Mapping[str, Any]] = None) -> None: ...

    def debug(self, message: str, **kw) -> None: ...
    def info(self, message: str, **kw) -> None: ...
    def warn(self, message: str, **kw) -> None: ...
    def error(self, message: str, **kw) -> None: ...
