from __future__ import annotations
from typing import Protocol, runtime_checkable, Iterable, Set, Tuple

@runtime_checkable
class IMarker(Protocol):
    def exists(self, name: str) -> bool: ...
    def set(self, name: str) -> None: ...
    def delete(self, name: str) -> None: ...
    def list(self, prefix: str) -> Iterable[str]: ...
    def require(self, required: Set[str]) -> Tuple[bool, Set[str]]: ...
