from __future__ import annotations
from typing import Protocol, runtime_checkable

@runtime_checkable
class IMarker(Protocol):
    """Интерфейс работы с маркерами в fs/markers/*"""
    def path_for(self, svc: str, name: str) -> str: ...
    def exists(self, svc: str, name: str) -> bool: ...
    def set(self, svc: str, name: str, payload: str | None = None) -> None: ...
    def delete(self, svc: str, name: str) -> None: ...
    def list(self, svc: str) -> list[str]: ...
    def require(self, required: set[str], svc: str) -> tuple[bool, set[str]]: ...
