from __future__ import annotations
from typing import Protocol, runtime_checkable, Set, Tuple, List

@runtime_checkable
class IMarkers(Protocol):
    """Интерфейс работы с маркерами"""
    def exists(self, name: str) -> bool: ...
    def set(self, name: str, payload: str | None = None) -> None: ...
    def delete(self, name: str) -> None: ...
    def list(self, prefix: str | None = None) -> list[str]: ...
    def require(self, required: set[str]) -> tuple[bool, set[str]]: ...
