from __future__ import annotations
from typing import Protocol, runtime_checkable, Mapping, Any

class _Counter(Protocol):
    def inc(self, labels: Mapping[str, str], value: int = 1) -> None: ...

class _Gauge(Protocol):
    def set(self, labels: Mapping[str, str], value: float) -> None: ...

class _Histogram(Protocol):
    def observe(self, labels: Mapping[str, str], value: float) -> None: ...

@runtime_checkable
class IMetrics(Protocol):
    def counter(self, name: str) -> _Counter: ...
    def gauge(self, name: str) -> _Gauge: ...
    def histogram(self, name: str) -> _Histogram: ...
