from __future__ import annotations
from typing import Protocol, Tuple, Optional

class INet(Protocol):
    def build_url(self, scheme: str, host: str, port: int, path: str = "/") -> str: ...
    def fqdn(self, host: str) -> str: ...
    def wait_port(self, host: str, port: int, *, timeout_ms: Optional[int] = None, interval_ms: Optional[int] = None) -> None: ...
    def probe_http(self, url: str, *, timeout_ms: Optional[int] = None) -> Tuple[int, bytes]: ...
    def probe_https(self, url: str, *, timeout_ms: Optional[int] = None) -> Tuple[int, bytes]: ...
