from __future__ import annotations
from typing import Protocol, runtime_checkable, Tuple

@runtime_checkable
class INet(Protocol):
    def build_url(self, scheme: str, host: str, port: int, path: str = "/", *, deadline_ms: int) -> str: ...
    def fqdn(self, host: str, *, deadline_ms: int) -> str: ...
    def wait_port(self, host: str, port: int, *, deadline_ms: int) -> None: ...
    def probe_http(self, url: str, *, deadline_ms: int) -> Tuple[int, bytes]: ...
    def probe_https(self, url: str, *, deadline_ms: int) -> Tuple[int, bytes]: ...
