from __future__ import annotations
from typing import Protocol, runtime_checkable, Optional

@runtime_checkable
class INet(Protocol):
    def build_url(self, host: str, port: int, path: str, *, https: bool = False) -> str: ...
    def fqdn(self, host: str) -> str: ...
    def wait_port(self, host: str, port: int) -> None: ...
    def probe_http(self, url: str, *, expected_status: int = 200) -> None: ...
    def probe_https(self, url: str, *, expected_status: int = 200) -> None: ...
