from __future__ import annotations
from typing import Protocol, runtime_checkable

@runtime_checkable
class IRegistrar(Protocol):
    def register(self, svc: str) -> None: ...
    def heartbeat(self, svc: str) -> None: ...
    def deregister(self, svc: str) -> None: ...
