from __future__ import annotations
from typing import Protocol, runtime_checkable

@runtime_checkable
class IService(Protocol):
    """
    Контракт жизненного цикла сервиса.
    Оркестрируется FSM. Без обязательных параметров дедлайна.
    """

    def initialize(self) -> None: ...
    def start(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def restart(self) -> None: ...
    def stop(self) -> None: ...
